name: Test CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        options:
          - dev
          - sandbox
          - stage
          - prod
        default: dev
        required: true
      environmentOption:
        type: choice
        description: 'EnvironmentOption'
        options:
          - bpmfin
          - bpmfin-a
          - bpmfin-b
        required: true
      tenantId:
        type: choice
        description: 'Tenant ID'
        options:
          - ganb
          - stc
          - jpbank
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.environment }}-${{ inputs.environmentOption }}, ${{ inputs.tenantId }}
