name: Test CI
run-name: '[${{ github.event.inputs.environment }}-${{ github.event.inputs.environmentOption }}][${{ github.event.inputs.tenantId }}][branchTag] Continuous Deployment'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        options:
          - dev
          - sandbox
          - stage
          - prod
          - pre1
          - pre2
          - pre3
          - pre4
        default: dev
        required: true
      environmentOption:
        type: choice
        description: 'EnvironmentOption'
        options:
          - bpmfin
          - bpmfin-a
          - bpmfin-b
        required: true
      tenantId:
        type: choice
        description: 'Tenant ID'
        options:
          - ganb
          - stc
          - jpbank
        required: true

jobs:
  tests:
    name: test action
    uses: ./.github/workflows/TestUseAction.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      environmentFile: ${{ github.event.inputs.environment }}-${{ github.event.inputs.environmentOption }}-${{ github.event.inputs.tenantId }}
      tenantId: ${{ github.event.inputs.tenantId }}
    secrets: inherit
